labels: ["New Compiler Pass"]
title: "[NEW PASS] "
body:

  - type: markdown
    attributes:
      value: |
        > #### _What's a "compiler pass?"_
        > In UCC (Unitary Compiler Collection), we consider any technique which takes a "raw" uncompiled quantum circuit and returns a circuit which performs better on our [benchmarks](https://github.com/unitaryfoundation/ucc-bench?tab=readme-ov-file#latest-results) to be a good compiler pass. You can work at any layer of the quantum computing stack, from low-level hardware control to high-level algorithmic optimization.

  - type: markdown
    attributes:
      value: |
        ### Propose your compiler pass
        So you want to implement a new compilation technique in UCC? Huzzah! To get started, please tell us:

  - type: textarea
    id: technique_work
    attributes:
      label: "1. How the technique works"
      description: |
        a. Provide a written abstract without too much jargon (cite arXiv paper/GitHub repo if applicable)  
        b. *(Optional)* Attach a diagram showing an example circuit transformation (you can add this later)
      value: |
        Example response:
        "This pass optimizes 2-qubit gate sequences using techniques from [Paper XYZ]. Here's how it transforms a CX gate sequence..."
    validations:
      required: true
  
  - type: textarea
    id: performance_expectations
    attributes:
      label: "2. Performance expectations"
      description: |
        a. What circuit types will this improve? (e.g., dynamic circuits, error correction)  
        b. Which [UCC metrics](https://ucc.readthedocs.io/en/latest/benchmarking.html) will it impact? (gate counts, errors, etc.)
      value: |
        Example response:
        "This should reduce 2-qubit gates in circuits with >50 Toffoli gates..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Important:** After filling out sections 1-2, scroll to the bottom of this page and click "Start discussion". **Leave the rest of the template below intact!** You'll be editing it later :)
        Maintainers will respond promptly to approve your proposal or provide feedback.        
